package br.com.sankhya.bhz.acoes;

import br.com.sankhya.extensions.actionbutton.AcaoRotinaJava;
import br.com.sankhya.extensions.actionbutton.ContextoAcao;
import br.com.sankhya.jape.dao.JdbcWrapper;
import br.com.sankhya.jape.sql.NativeSql;
import br.com.sankhya.modelcore.util.EntityFacadeFactory;

public class acaoImportacao implements AcaoRotinaJava {
    @Override
    public void doAction(ContextoAcao contextoAcao) throws Exception {
        JdbcWrapper jdbc = EntityFacadeFactory.getDWFFacade().getJdbcWrapper();
        jdbc.openSession();
        NativeSql sql = new NativeSql(jdbc);
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	24000	, ESTMAX=	30000	WHERE CODPROD = 	361	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	24000	, ESTMAX=	30000	WHERE CODPROD = 	455	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	800	, ESTMAX=	1800	WHERE CODPROD = 	636	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	500	, ESTMAX=	1500	WHERE CODPROD = 	691	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	530	, ESTMAX=	1086	WHERE CODPROD = 	692	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	510	, ESTMAX=	1066	WHERE CODPROD = 	693	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	1520	, ESTMAX=	2076	WHERE CODPROD = 	694	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	1300	, ESTMAX=	1856	WHERE CODPROD = 	695	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	470	, ESTMAX=	1026	WHERE CODPROD = 	696	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	1100	, ESTMAX=	2100	WHERE CODPROD = 	697	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	930	, ESTMAX=	1930	WHERE CODPROD = 	698	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	545	, ESTMAX=	1545	WHERE CODPROD = 	699	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	825	, ESTMAX=	1825	WHERE CODPROD = 	700	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	700	, ESTMAX=	1700	WHERE CODPROD = 	701	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	110	, ESTMAX=	1110	WHERE CODPROD = 	712	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	230	, ESTMAX=	1230	WHERE CODPROD = 	713	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	150	, ESTMAX=	1150	WHERE CODPROD = 	714	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	150	, ESTMAX=	1150	WHERE CODPROD = 	715	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	170	, ESTMAX=	1170	WHERE CODPROD = 	716	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	180	, ESTMAX=	1180	WHERE CODPROD = 	718	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	140	, ESTMAX=	1140	WHERE CODPROD = 	719	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	140	, ESTMAX=	1140	WHERE CODPROD = 	720	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	190	, ESTMAX=	1190	WHERE CODPROD = 	721	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	210	, ESTMAX=	1210	WHERE CODPROD = 	732	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	270	, ESTMAX=	1270	WHERE CODPROD = 	733	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	320	, ESTMAX=	1320	WHERE CODPROD = 	734	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	100	, ESTMAX=	1100	WHERE CODPROD = 	736	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	125	, ESTMAX=	1125	WHERE CODPROD = 	737	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	100	, ESTMAX=	1100	WHERE CODPROD = 	738	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	120	, ESTMAX=	1120	WHERE CODPROD = 	739	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	165	, ESTMAX=	1165	WHERE CODPROD = 	740	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	65	, ESTMAX=	1065	WHERE CODPROD = 	741	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	125	, ESTMAX=	1125	WHERE CODPROD = 	742	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	180	, ESTMAX=	1180	WHERE CODPROD = 	743	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	70	, ESTMAX=	1070	WHERE CODPROD = 	744	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	210	, ESTMAX=	1210	WHERE CODPROD = 	745	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	150	, ESTMAX=	1150	WHERE CODPROD = 	746	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	140	, ESTMAX=	1140	WHERE CODPROD = 	747	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	65	, ESTMAX=	1065	WHERE CODPROD = 	748	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	70	, ESTMAX=	1070	WHERE CODPROD = 	749	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	60	, ESTMAX=	1060	WHERE CODPROD = 	750	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	180	, ESTMAX=	1180	WHERE CODPROD = 	722	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	160	, ESTMAX=	1160	WHERE CODPROD = 	723	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	180	, ESTMAX=	1180	WHERE CODPROD = 	724	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	340	, ESTMAX=	1340	WHERE CODPROD = 	725	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	120	, ESTMAX=	1120	WHERE CODPROD = 	726	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	130	, ESTMAX=	1130	WHERE CODPROD = 	727	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	80	, ESTMAX=	1080	WHERE CODPROD = 	728	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	150	, ESTMAX=	1150	WHERE CODPROD = 	729	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	35	, ESTMAX=	1035	WHERE CODPROD = 	730	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	980	, ESTMAX=	1980	WHERE CODPROD = 	702	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	1200	, ESTMAX=	2200	WHERE CODPROD = 	703	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	1400	, ESTMAX=	2400	WHERE CODPROD = 	704	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	960	, ESTMAX=	1960	WHERE CODPROD = 	705	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	370	, ESTMAX=	1370	WHERE CODPROD = 	706	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	165	, ESTMAX=	1165	WHERE CODPROD = 	707	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	120	, ESTMAX=	1120	WHERE CODPROD = 	708	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	300	, ESTMAX=	1300	WHERE CODPROD = 	709	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	330	, ESTMAX=	1330	WHERE CODPROD = 	710	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	240	, ESTMAX=	1240	WHERE CODPROD = 	711	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	0	, ESTMAX=	1000	WHERE CODPROD = 	680	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	0	, ESTMAX=	1000	WHERE CODPROD = 	682	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	0	, ESTMAX=	1000	WHERE CODPROD = 	683	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	600	, ESTMAX=	1600	WHERE CODPROD = 	686	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	100	, ESTMAX=	1100	WHERE CODPROD = 	687	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	520	, ESTMAX=	1520	WHERE CODPROD = 	688	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	300	, ESTMAX=	1300	WHERE CODPROD = 	689	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	500	, ESTMAX=	1500	WHERE CODPROD = 	690	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	20	, ESTMAX=	1020	WHERE CODPROD = 	774	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	40	, ESTMAX=	1040	WHERE CODPROD = 	775	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	30	, ESTMAX=	1030	WHERE CODPROD = 	776	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	40	, ESTMAX=	1040	WHERE CODPROD = 	777	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	35	, ESTMAX=	1035	WHERE CODPROD = 	778	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	40	, ESTMAX=	1040	WHERE CODPROD = 	779	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	20	, ESTMAX=	1020	WHERE CODPROD = 	780	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	40	, ESTMAX=	1040	WHERE CODPROD = 	781	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	20	, ESTMAX=	1020	WHERE CODPROD = 	782	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	40	, ESTMAX=	1040	WHERE CODPROD = 	783	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	20	, ESTMAX=	1020	WHERE CODPROD = 	784	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	100	, ESTMAX=	1100	WHERE CODPROD = 	786	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	160	, ESTMAX=	1160	WHERE CODPROD = 	787	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	100	, ESTMAX=	1100	WHERE CODPROD = 	788	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	160	, ESTMAX=	1160	WHERE CODPROD = 	789	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	800	, ESTMAX=	1800	WHERE CODPROD = 	790	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	220	, ESTMAX=	1220	WHERE CODPROD = 	791	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	330	, ESTMAX=	1330	WHERE CODPROD = 	792	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	800	, ESTMAX=	1800	WHERE CODPROD = 	793	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	800	, ESTMAX=	1800	WHERE CODPROD = 	794	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	0	, ESTMAX=	1000	WHERE CODPROD = 	795	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	0	, ESTMAX=	1000	WHERE CODPROD = 	796	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	830	, ESTMAX=	1830	WHERE CODPROD = 	797	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	850	, ESTMAX=	1850	WHERE CODPROD = 	798	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	280	, ESTMAX=	1280	WHERE CODPROD = 	799	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	8000	, ESTMAX=	9000	WHERE CODPROD = 	800	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	300	, ESTMAX=	1300	WHERE CODPROD = 	801	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	85	, ESTMAX=	1085	WHERE CODPROD = 	752	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	80	, ESTMAX=	1080	WHERE CODPROD = 	753	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	70	, ESTMAX=	1070	WHERE CODPROD = 	754	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	210	, ESTMAX=	1210	WHERE CODPROD = 	755	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	200	, ESTMAX=	1200	WHERE CODPROD = 	756	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	310	, ESTMAX=	1310	WHERE CODPROD = 	757	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	30	, ESTMAX=	1030	WHERE CODPROD = 	758	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	275	, ESTMAX=	1275	WHERE CODPROD = 	759	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	380	, ESTMAX=	1380	WHERE CODPROD = 	760	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	120	, ESTMAX=	1120	WHERE CODPROD = 	761	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	185	, ESTMAX=	1185	WHERE CODPROD = 	762	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	450	, ESTMAX=	1450	WHERE CODPROD = 	763	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	235	, ESTMAX=	1235	WHERE CODPROD = 	764	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	245	, ESTMAX=	1245	WHERE CODPROD = 	765	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	480	, ESTMAX=	1480	WHERE CODPROD = 	766	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	270	, ESTMAX=	1270	WHERE CODPROD = 	767	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	231	, ESTMAX=	1231	WHERE CODPROD = 	768	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	40	, ESTMAX=	80	WHERE CODPROD = 	769	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	35	, ESTMAX=	70	WHERE CODPROD = 	770	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	50	, ESTMAX=	100	WHERE CODPROD = 	771	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	20	, ESTMAX=	40	WHERE CODPROD = 	772	");
        sql.executeUpdate("	UPDATE TGFPRO SET ESTMIN=	50	, ESTMAX=	100	WHERE CODPROD = 	773	");

        contextoAcao.setMensagemRetorno("Processo Finalizado!!!");
    }
}
